version: '3.3'
services:
  postgres:
    image: 'postgres:10.4'
    ports:
      - '32768:5432'
    volumes:
      - '$HOME/Docker volumes/postgresql/10.4:/var/lib/postgresql/data'
  redis:
    image: 'redis:4.0.11'
    ports:
      - '32769:6379'
    volumes: []